import { getRandom5DigitNumber, getRandomElement } from '../../utils';

const street_types = [
  'Street',
  'Avenue',
  'Boulevard',
  'Lane',
  'Road',
  'Drive',
  'Court',
  'Place',
  'Circle',
  'Way',
  'Terrace',
  'Square',
  'Plaza',
  'Trail',
  'Parkway',
];

const street_names = [
  'Main',
  'Park',
  'Elm',
  'Maple',
  'Oak',
  'Pine',
  'Cedar',
  'Birch',
  'River',
  'Lake',
  'Sunset',
  'Ocean',
  'Hill',
  'Valley',
  'Meadow',
  'Grove',
  'Forest',
  'Spring',
  'Summer',
  'Winter',
  'Autumn',
  'West',
  'East',
  'North',
  'South',
  'Central',
  'High',
  'Low',
  'Broad',
  'Narrow',
  'First',
  'Second',
  'Third',
  'Fourth',
  'Fifth',
  'Sixth',
  'Seventh',
  'Eighth',
  'Ninth',
  'Tenth',
  'Milton',
  'Springfield',
  'West Mauna Loa',
  'East Main',
  'Sable Run',
  'Martin Luther King Junior',
  'Saint John',
  'George Washington',
  'John Adams',
  'Thomas Jefferson',
  'James Madison',
  'James Monroe',
  'John Quincy Adams',
  'Andrew Jackson',
  'Martin Van Buren',
  'William Henry Harrison',
  'John Tyler',
  'James K. Polk',
  'Zachary Taylor',
  'Millard Fillmore',
  'Franklin Pierce',
  'James Buchanan',
  'Abraham Lincoln',
  'Andrew Johnson',
  'Ulysses S. Grant',
  'Rutherford B. Hayes',
  'James A. Garfield',
  'Chester A. Arthur',
  'Grover Cleveland',
  'Benjamin Harrison',
  'Grover Cleveland',
  'William McKinley',
  'Theodore Roosevelt',
  'William Howard Taft',
  'Woodrow Wilson',
  'Warren G. Harding',
  'Calvin Coolidge',
  'Herbert Hoover',
  'Franklin D. Roosevelt',
  'Harry S. Truman',
  'Dwight D. Eisenhower',
  'John F. Kennedy',
  'Lyndon B. Johnson',
  'Richard Nixon',
  'Gerald Ford',
  'Jimmy Carter',
  'Ronald Reagan',
  'George H. W. Bush',
  'Bill Clinton',
  'George W. Bush',
  'Barack Obama',
  'Donald Trump',
  'Joe Biden',
  'Manuel Blanco Encalada',
  'Ramón Freire',
  'Francisco Antonio Pinto',
  'Francisco Ramón Vicuña',
  'José Joaquín Prieto',
  'Manuel Bulnes',
  'Manuel Montt',
  'José Joaquín Pérez',
  'Federico Errázuriz Zañartu',
  'Aníbal Pinto',
  'Domingo Santa María',
  'Manuel Balmaceda',
  'Jorge Montt',
  'Federico Errázuriz Echaurren',
  'Aníbal Zañartu',
  'Germán Riesco',
  'Pedro Montt',
  'Ramón Barros Luco',
  'Juan Luis Sanfuentes',
  'Arturo Alessandri',
  'Luis Altamirano',
  'Pedro Aguirre Cerda',
  'Juan Antonio Ríos',
  'Gabriel González Videla',
  'Carlos Ibáñez del Campo',
  'Jorge Alessandri',
  'Eduardo Frei Montalva',
  'Salvador Allende',
  'Augusto Pinochet',
  'Patricio Aylwin',
  'Eduardo Frei Ruiz-Tagle',
  'Ricardo Lagos',
  'Michelle Bachelet',
  'Sebastián Piñera',
  'Gabriel Boric',
  'Hirobumi Itō',
  'Kiyotaka Kuroda',
  'Shigenobu Ōkuma',
  'Hirobumi Itō',
  'Aritomo Yamagata',
  'Masayoshi Matsukata',
  'Hirobumi Itō',
  'Shigenobu Ōkuma',
  'Taro Katsura',
  'Ōkuma Shigenobu',
  'Takaaki Kato',
  'Ōkuma Shigenobu',
  'Masatake Terauchi',
  'Hara Takashi',
  'Kijūrō Shidehara',
  'Keigo Kiyoura',
  'Takaaki Kato',
  'Osachi Hamaguchi',
  'Reijirō Wakatsuki',
  'Tsuyoshi Inukai',
  'Makoto Saito',
  'Keisuke Okada',
  'Kōki Hirota',
  'Kiichirō Hiranuma',
  'Hideki Tōjō',
  'Kuniaki Koiso',
  'Naruhiko Higashikuni',
  'Kijūrō Shidehara',
  'Shigeru Yoshida',
  'Tetsu Katayama',
  'Hitoshi Ashida',
  'Shigeru Yoshida',
  'Ichirō Hatoyama',
  'Taketora Ogata',
  'Ichirō Hatoyama',
  'Nobusuke Kishi',
  'Hayato Ikeda',
  'Eisaku Satō',
  'Kakuei Tanaka',
  'Takeo Miki',
  'Takeo Fukuda',
  'Masayoshi Ōhira',
  'Zenkō Suzuki',
  'Yasuhiro Nakasone',
  'Noboru Takeshita',
  'Sōsuke Uno',
  'Toshiki Kaifu',
  'Kiichi Miyazawa',
  'Yoshiro Mori',
  'Junichiro Koizumi',
  'Shinzo Abe',
  'Yasuo Fukuda',
  'Taro Aso',
  'Yukio Hatoyama',
  'Naoto Kan',
  'Yoshihiko Noda',
  'Shinzo Abe',
  'Yoshihide Suga',
  'Fumio Kishida',
  'Yasuo Fukuda',
  'Taro Aso',
  'Yukio Hatoyama',
  'Naoto Kan',
  'Yoshihiko Noda',
  'Shinzo Abe',
  'Yoshihide Suga',
  'Fumio Kishida',
  'Nile River',
  'Tigris River',
  'Euphrates River',
  'Indus River',
  'Yellow River',
  'Yangtze River',
  'Ganges River',
  'Danube River',
  'Rhine River',
  'Amazon River',
  'Mississippi River',
  'Tigris-Euphrates',
  'Ganges-Brahmaputra',
  'Mekong River',
  'Volga River',
  'Congo River',
  'Rio Grande',
  'Yukon River',
  'Niger River',
  'Murray-Darling River System',
  'Kabul',
  'Tirana',
  'Algiers',
  'Andorra la Vella',
  'Luanda',
  "Saint John's",
  'Buenos Aires',
  'Yerevan',
  'Canberra',
  'Vienna',
  'Baku',
  'Nassau',
  'Manama',
  'Dhaka',
  'Bridgetown',
  'Minsk',
  'Brussels',
  'Belmopan',
  'Porto-Novo',
  'Thimphu',
  'Sucre',
  'Sarajevo',
  'Gaborone',
  'Brasília',
  'Bandar Seri Begawan',
  'Sofia',
  'Ouagadougou',
  'Bujumbura',
  'Phnom Penh',
  'Yaoundé',
  'Ottawa',
  'Praia',
  'Bangui',
  "N'Djamena",
  'Santiago',
  'Beijing',
  'Bogotá',
  'Moroni',
  'Brazzaville',
  'San José',
  'Zagreb',
  'Havana',
  'Nicosia',
  'Prague',
  'Kinshasa',
  'Copenhagen',
  'Djibouti (city)',
  'Roseau',
  'Santo Domingo',
  'Quito',
  'Cairo',
  'San Salvador',
  'Malabo',
  'Asmara',
  'Tallinn',
  'Mbabane',
  'Addis Ababa',
  'Suva',
  'Helsinki',
  'Paris',
  'Libreville',
  'Banjul',
  'Tbilisi',
  'Berlin',
  'Accra',
  'Athens',
  "Saint George's",
  'Guatemala City',
  'Conakry',
  'Bissau',
  'Georgetown',
  'Port-au-Prince',
  'Tegucigalpa',
  'Budapest',
  'Reykjavík',
  'New Delhi',
  'Jakarta',
  'Tehran',
  'Baghdad',
  'Dublin',
  'Jerusalem',
  'Rome',
  'Kingston',
  'Tokyo',
  'Amman',
  'Astana',
  'Nairobi',
  'South Tarawa',
  'Pristina',
  'Kuwait City',
  'Bishkek',
  'Vientiane',
  'Riga',
  'Beirut',
  'Maseru',
  'Monrovia',
  'Tripoli',
  'Vaduz',
  'Vilnius',
  'Luxembourg (city)',
  'Skopje',
  'Antananarivo',
  'Lilongwe',
  'Kuala Lumpur',
  'Malé',
  'Bamako',
  'Valletta',
  'Majuro',
  'Nouakchott',
  'Port Louis',
  'Mexico City',
  'Palikir',
  'Chisinau',
  'Monaco',
  'Ulaanbaatar',
  'Podgorica',
  'Rabat',
  'Maputo',
  'Naypyidaw',
  'Windhoek',
  'Yaren',
  'Kathmandu',
  'Amsterdam',
  'Wellington',
  'Managua',
  'Niamey',
  'Abuja',
  'Pyongyang',
  'Oslo',
  'Muscat',
  'Islamabad',
  'Ngerulmud',
  'Jerusalem (East)',
  'Panama City',
  'Port Moresby',
  'Asunción',
  'Lima',
  'Manila',
  'Warsaw',
  'Lisbon',
  'Doha',
  'Bucharest',
  'Moscow',
  'Kigali',
  'Basseterre',
  'Castries',
  'Kingstown',
  'Apia',
  'San Marino',
  'São Tomé',
  'Riyadh',
  'Dakar',
  'Belgrade',
  'Victoria',
  'Freetown',
  'Singapore',
  'Bratislava',
  'Ljubljana',
  'Honiara',
  'Mogadishu',
  'Pretoria',
  'Juba',
  'Madrid',
  'Colombo',
  'Khartoum',
  'Paramaribo',
  'Mbabane (administrative)',
  'Stockholm',
  'Bern',
  'Damascus',
  'Taipei',
  'Dushanbe',
  'Dodoma',
  'Bangkok',
  'Dili',
  'Lomé',
  "Nuku'alofa",
  'Port of Spain',
  'Tunis',
  'Ankara',
  'Ashgabat',
  'Funafuti',
  'Kampala',
  'Kyiv',
  'Abu Dhabi',
  'London',
  'Washington, D.C.',
  'Montevideo',
  'Tashkent',
  'Port Vila',
  'Vatican City',
  'Caracas',
  'Hanoi',
  "Sana'a",
  'Lusaka',
  'Harare',
  'Mount Everest',
  'K2',
  'Kangchenjunga',
  'Lhotse',
  'Makalu',
  'Cho Oyu',
  'Dhaulagiri',
  'Manaslu',
  'Nanga Parbat',
  'Annapurna',
  'Gasherbrum I',
  'Broad Peak',
  'Gasherbrum II',
  'Shishapangma',
  'Gyachung Kang',
  'Gasherbrum III',
  'Annapurna II',
  'Gasherbrum IV',
  'Himalchuli',
  'Distaghil Sar',
  'Ngadi Chuli',
  'Nuptse',
  'Khunyang Chhish',
  'Masherbrum',
  'Nanda Devi',
  'Chomo Lonzo',
  'Batura Sar',
  'Kanjut Sar',
  'Rakaposhi',
  'Namcha Barwa',
  'Kamet',
  'Tirich Mir',
  'Jannu',
  'Dhaulagiri II',
  'Chogolisa',
  'Annapurna III',
  'Nanda Kot',
  'Yangra',
  'Mamostong Kangri',
  'Kangpenqing',
  'Annapurna Dakshin',
  'Kula Kangri',
  'Saltoro Kangri',
  'Sia Kangri',
  'Teram Kangri',
  'Baltistan Peak',
  'Rimo I',
  'Chamlang',
  'Labuche Kang',
  'Skil Brum',
  'Siguang Ri',
  'The Crown',
  'Tongshanjiabu',
  'Narmer',
  'Djer',
  'Djet',
  'Den',
  'Anedjib',
  'Semerkhet',
  "Qa'a",
  'Hotepsekhemwy',
  'Nebra',
  'Neithhotep',
  'Sneferka',
  'Horus Bird',
  'Sekhemkhet',
  'Sanakht',
  'Weneg',
  'Wadjenes',
  'Senedj',
  'Seth-Peribsen',
  "Sekhemib-Perenma'at",
  'Khasekhemwy',
  'Djoser',
  'Khaba',
  'Netjerykhet (Djoser)',
  'Huni',
  'Snofru',
  'Khufu',
  'Djedefre',
  'Khafre',
  'Bikheris',
  'Menkaure',
  'Shepseskaf',
  'Userkaf',
  'Sahure',
  'Neferirkare Kakai',
  'Shepseskare',
  'Neferefre',
  'Nyuserre Ini',
  'Menkauhor Kaiu',
  'Djedkare Isesi',
  'Unas',
  'Teti',
  'Userkare',
  'Pepi I',
  'Merenre Nemtyemsaf I',
  'Pepi II Neferkare',
  'Nitiqret',
  'Nitocris',
  'Merenre II',
  'Merenre Nemtyemsaf II',
  'Neitiqerty Siptah',
  'Merenhor',
  'Netjerkare Siptah',
  'Menkare',
  'Nikare',
  'Neferkare II',
  'Neferkare III',
  'Djedkare Shemai',
  'Neferkare IV',
  'Khakherewre',
  'Neferirkare',
  'Khaneferre Sobekhotep',
  'Khaneferre Sobekhotep II',
  'Khaneferre Sobekhotep III',
  'Khaneferre Sobekhotep IV',
  'Merhotepre Sobekhotep',
  'Khahotepre Sobekhotep',
  'Amenemhat I',
  'Senusret I',
  'Amenemhat II',
  'Senusret II',
  'Amenemhat III',
  'Amenemhat IV',
  'Sobekneferu',
  'Sehetepkare Intef I',
  'Iyibkhentre Intef II',
  'Seankhibre Ameny Antef Amenemhet VI',
  'Nubkheperre Intef III',
  'Sekhemre Sankhtawy Neferhotep III',
  'Sanakhte Nebmaatre',
  'Sobekhotep I',
  'Renseneb',
  'Sobekhotep II',
  'Semerkare',
  'Ibiaw',
  'Sewadjkare',
  'Nedjemibre',
  'Sobekemsaf I',
  'Reniseneb',
  'Hor I',
  'Hor II',
  'Amenemhat V',
  'Sobekemsaf II',
  'Khendjer',
  'Imyremeshaw',
  'Sehetepkare Intef II',
  'Sewadjkare Hori',
  'Merikare',
  'Sewadjtu',
  'Merkawre Sobekhotep',
  'Mersekhemre Ined',
  'Sewadjkare III',
  'Nikare II',
  'Sobekhotep III',
  'Neferhotep I',
  'Sihathor',
  'Sobekhotep IV',
  'Merhotepre Ini',
  'Seankhenre Mentuhotepi',
  'Sehetepkare Intef III',
  'Seankhenre Montuhotep VI',
  'Semenenre I',
  'Seuserenre Bebiankh',
  'Sekhemre Shedwaset',
  'Sekhemre Wadjkhaw Sobekemsaf',
  'Sekhemre Shedtawy Sobekemsaf',
  'Yakareb',
  'Qareh',
  "Ya'ammu Nubwoserre",
  'Kahusy',
  'Iytjenu',
  'Maatkare',
  'Ameny Antef Amenemhat VII',
  'Nikare III',
  'Sekhemre Sankhtawy Neferhotep II',
  'Sekhemre Wadjkhaw Sobekemsaf II',
  'Sewadjare Mentuhotep',
  'Nehesy',
  'Sobekhotep V',
  'Iufni',
  'Amu',
  'Siamun',
  'Tao I',
  'Tao II',
  'Pedubast I',
  'Shoshenq I',
  'Osorkon I',
  'Shoshenq II',
  'Takelot I',
  'Osorkon II',
  'Shoshenq III',
  'Shoshenq IV',
  'Pami',
  'Shoshenq V',
  'Osorkon IV',
  'Takelot II',
  'Shoshenq VI',
  'Osorkon III',
  'Takelot III',
  'Rudamun',
  'Ini',
  'Psusennes I',
  'Amenemope',
  'Shoshenq VII',
  'Shoshenq VIII',
  'Ankhefensekhmet',
  'Ankhefenmut',
  'Psusennes II',
  'Peter',
  'Linus',
  'Anacletus',
  'Clement I',
  'Evaristus',
  'Alexander I',
  'Sixtus I',
  'Telesphorus',
  'Hyginus',
  'Pius I',
  'Anicetus',
  'Soter',
  'Eleutherius',
  'Victor I',
  'Zephyrinus',
  'Callixtus I',
  'Urban I',
  'Pontian',
  'Anterus',
  'Fabian',
  'Cornelius',
  'Lucius I',
  'Stephen I',
  'Sixtus II',
  'Dionysius',
  'Felix I',
  'Eutychian',
  'Caius',
  'Marcellinus',
  'Marcellus I',
  'Eusebius',
  'Miltiades',
  'Sylvester I',
  'Mark',
  'Julius I',
  'Liberius',
  'Damasus I',
  'Siricius',
  'Anastasius I',
  'Innocent I',
  'Zosimus',
  'Boniface I',
  'Celestine I',
  'Sixtus III',
  'Leo I',
  'Hilarius',
  'Simplicius',
  'Felix III',
  'Gelasius I',
  'Anastasius II',
  'Symmachus',
  'Hormisdas',
  'John I',
  'Felix IV',
  'Boniface II',
  'John II',
  'Agapetus I',
  'Silverius',
  'Vigilius',
  'Pelagius I',
  'John III',
  'Benedict I',
  'Pelagius II',
  'Gregory I',
  'Sabinian',
  'Boniface III',
  'Boniface IV',
  'Adeodatus I',
  'Boniface V',
  'Honorius I',
  'Severinus',
  'John IV',
  'Theodore I',
  'Martin I',
  'Eugene I',
  'Vitalian',
  'Adeodatus II',
  'Donus',
  'Agatho',
  'Leo II',
  'Benedict II',
  'John V',
  'Conon',
  'Sergius I',
  'John VI',
  'John VII',
  'Sisinnius',
  'Constantine',
  'Gregory II',
  'Gregory III',
  'Zachary',
  'Stephen II',
  'Paul I',
  'Stephen III',
  'Adrian I',
  'Leo III',
  'Stephen IV',
  'Paschal I',
  'Eugene II',
  'Valentine',
  'Gregory IV',
  'Sergius II',
  'Leo IV',
  'Benedict III',
  'Nicholas I',
  'Adrian II',
  'John VIII',
  'Marinus I',
  'Adrian III',
  'Stephen V',
  'Formosus',
  'Boniface VI',
  'Stephen VI',
  'Romanus',
  'Theodore II',
  'John IX',
  'Benedict IV',
  'Leo V',
  'Sergius III',
  'Anastasius III',
  'Lando',
  'John X',
  'Leo VI',
  'Stephen VII',
  'John XI',
  'Leo VII',
  'Stephen VIII',
  'Marinus II',
  'Agapetus II',
  'John XII',
  'Leo VIII',
  'Benedict V',
  'John XIII',
  'Benedict VI',
  'Benedict VII',
  'John XIV',
  'John XV',
  'Gregory V',
  'Sylvester II',
  'John XVII',
  'John XVIII',
  'Sergius IV',
  'Benedict VIII',
  'John XIX',
  'Benedict IX',
  'Silvester III',
  'Benedict IX',
  'Gregory VI',
  'Clement II',
  'Damasus II',
  'Leo IX',
  'Victor II',
  'Stephen IX',
  'Nicholas II',
  'Alexander II',
  'Gregory VII',
  'Victor III',
  'Urban II',
  'Paschal II',
  'Gelasius II',
  'Callixtus II',
  'Honorius II',
  'Innocent II',
  'Celestine II',
  'Lucius II',
  'Eugene III',
  'Anastasius IV',
  'Adrian IV',
  'Alexander III',
  'Lucius III',
  'Urban III',
  'Gregory VIII',
  'Clement III',
  'Celestine III',
  'Innocent III',
  'Honorius III',
  'Gregory IX',
  'Celestine IV',
  'Innocent IV',
  'Alexander IV',
  'Urban IV',
  'Clement IV',
  'Gregory X',
  'Innocent V',
  'Adrian V',
  'John XXI',
  'Nicholas III',
  'Martin IV',
  'Honorius IV',
  'Nicholas IV',
  'Celestine V',
  'Boniface VIII',
  'Benedict XI',
  'Clement V',
  'John XXII',
  'Benedict XII',
  'Clement VI',
  'Innocent VI',
  'Urban V',
  'Gregory XI',
  'Urban VI',
  'Boniface IX',
  'Innocent VII',
  'Gregory XII',
  'Martin V',
  'Eugene IV',
  'Nicholas V',
  'Callixtus III',
  'Pius II',
  'Paul II',
  'Sixtus IV',
  'Innocent VIII',
  'Alexander VI',
  'Pius III',
  'Julius II',
  'Leo X',
  'Adrian VI',
  'Clement VII',
  'Paul III',
  'Julius III',
  'Marcellus II',
  'Paul IV',
  'Pius IV',
  'Pius V',
  'Gregory XIII',
  'Sixtus V',
  'Urban VII',
  'Gregory XIV',
  'Innocent IX',
];

export function generateRandomStreetAddress() {
  return {
    name: getRandomElement(street_types) + ' ' + getRandomElement(street_names),
    number: getRandom5DigitNumber(),
  };
}
